name = "FlowGeometries"
uuid = "0ccd6995-f618-4175-b01e-f437d0cb4974"
version = "0.1.0"
authors = ["Jordan Benjamin <jordantbenjamin@gmail.com>"]

[workspace]
projects = ["test"]

[weakdeps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ComputationalBackends = "5c6e2104-4040-447f-8fc0-66ec2223b019"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Quickhull = "baca2653-9c88-49d2-a488-12dbf25fc4fb"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
FlowGeometriesAbstractFFTsExt = "AbstractFFTs"
FlowGeometriesAdaptExt = "Adapt"
FlowGeometriesComputationalBackendsExt = "ComputationalBackends"
FlowGeometriesDelaunayTriangulationExt = "DelaunayTriangulation"
FlowGeometriesKernelAbstractionsExt = "KernelAbstractions"
FlowGeometriesNearestNeighborsExt = "NearestNeighbors"
FlowGeometriesQuickhullExt = "Quickhull"
FlowGeometriesSparseArraysExt = "SparseArrays"
FlowGeometriesStaticArraysExt = "StaticArrays"

[compat]
AbstractFFTs = "1"
Adapt = "4"
ComputationalBackends = "0.1, 1"
DelaunayTriangulation = "1"
KernelAbstractions = "0.9, 1"
NearestNeighbors = "0.4.28"
Quickhull = "0.2"
SparseArrays = "1.11"
StaticArrays = "1"
julia = "1.11"
